/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace EventTicketing {
  export type EventStruct = {
    organizer: AddressLike;
    name: string;
    date: BigNumberish;
    price: BigNumberish;
    totalTickets: BigNumberish;
    ticketsRemaining: BigNumberish;
    fundsCollected: BigNumberish;
  };

  export type EventStructOutput = [
    organizer: string,
    name: string,
    date: bigint,
    price: bigint,
    totalTickets: bigint,
    ticketsRemaining: bigint,
    fundsCollected: bigint
  ] & {
    organizer: string;
    name: string;
    date: bigint;
    price: bigint;
    totalTickets: bigint;
    ticketsRemaining: bigint;
    fundsCollected: bigint;
  };
}

export interface EventTicketingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyTickets"
      | "createEvent"
      | "getEvent"
      | "getUserTickets"
      | "nextEventId"
      | "ticketsOwned"
      | "transferTickets"
      | "withdrawFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EventCreated"
      | "FundsWithdrawn"
      | "TicketsPurchased"
      | "TicketsTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyTickets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createEvent",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEvent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTickets",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextEventId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ticketsOwned",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferTickets",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFunds",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "buyTickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createEvent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEvent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextEventId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ticketsOwned",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferTickets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFunds",
    data: BytesLike
  ): Result;
}

export namespace EventCreatedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    organizer: AddressLike,
    name: string,
    date: BigNumberish,
    price: BigNumberish,
    totalTickets: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    organizer: string,
    name: string,
    date: bigint,
    price: bigint,
    totalTickets: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    organizer: string;
    name: string;
    date: bigint;
    price: bigint;
    totalTickets: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsWithdrawnEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    organizer: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    organizer: string,
    amount: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    organizer: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketsPurchasedEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    buyer: AddressLike,
    quantity: BigNumberish
  ];
  export type OutputTuple = [eventId: bigint, buyer: string, quantity: bigint];
  export interface OutputObject {
    eventId: bigint;
    buyer: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketsTransferredEvent {
  export type InputTuple = [
    eventId: BigNumberish,
    from: AddressLike,
    to: AddressLike,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    eventId: bigint,
    from: string,
    to: string,
    quantity: bigint
  ];
  export interface OutputObject {
    eventId: bigint;
    from: string;
    to: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EventTicketing extends BaseContract {
  connect(runner?: ContractRunner | null): EventTicketing;
  waitForDeployment(): Promise<this>;

  interface: EventTicketingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyTickets: TypedContractMethod<
    [_eventId: BigNumberish, _quantity: BigNumberish],
    [void],
    "payable"
  >;

  createEvent: TypedContractMethod<
    [
      _name: string,
      _date: BigNumberish,
      _price: BigNumberish,
      _totalTickets: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent: TypedContractMethod<
    [_eventId: BigNumberish],
    [EventTicketing.EventStructOutput],
    "view"
  >;

  getUserTickets: TypedContractMethod<
    [_user: AddressLike, _eventId: BigNumberish],
    [bigint],
    "view"
  >;

  nextEventId: TypedContractMethod<[], [bigint], "view">;

  ticketsOwned: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  transferTickets: TypedContractMethod<
    [_eventId: BigNumberish, _quantity: BigNumberish, _to: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFunds: TypedContractMethod<
    [_eventId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyTickets"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _quantity: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createEvent"
  ): TypedContractMethod<
    [
      _name: string,
      _date: BigNumberish,
      _price: BigNumberish,
      _totalTickets: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getEvent"
  ): TypedContractMethod<
    [_eventId: BigNumberish],
    [EventTicketing.EventStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTickets"
  ): TypedContractMethod<
    [_user: AddressLike, _eventId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextEventId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ticketsOwned"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferTickets"
  ): TypedContractMethod<
    [_eventId: BigNumberish, _quantity: BigNumberish, _to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawFunds"
  ): TypedContractMethod<[_eventId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "EventCreated"
  ): TypedContractEvent<
    EventCreatedEvent.InputTuple,
    EventCreatedEvent.OutputTuple,
    EventCreatedEvent.OutputObject
  >;
  getEvent(
    key: "FundsWithdrawn"
  ): TypedContractEvent<
    FundsWithdrawnEvent.InputTuple,
    FundsWithdrawnEvent.OutputTuple,
    FundsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "TicketsPurchased"
  ): TypedContractEvent<
    TicketsPurchasedEvent.InputTuple,
    TicketsPurchasedEvent.OutputTuple,
    TicketsPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "TicketsTransferred"
  ): TypedContractEvent<
    TicketsTransferredEvent.InputTuple,
    TicketsTransferredEvent.OutputTuple,
    TicketsTransferredEvent.OutputObject
  >;

  filters: {
    "EventCreated(uint256,address,string,uint256,uint256,uint256)": TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;
    EventCreated: TypedContractEvent<
      EventCreatedEvent.InputTuple,
      EventCreatedEvent.OutputTuple,
      EventCreatedEvent.OutputObject
    >;

    "FundsWithdrawn(uint256,address,uint256)": TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;
    FundsWithdrawn: TypedContractEvent<
      FundsWithdrawnEvent.InputTuple,
      FundsWithdrawnEvent.OutputTuple,
      FundsWithdrawnEvent.OutputObject
    >;

    "TicketsPurchased(uint256,address,uint256)": TypedContractEvent<
      TicketsPurchasedEvent.InputTuple,
      TicketsPurchasedEvent.OutputTuple,
      TicketsPurchasedEvent.OutputObject
    >;
    TicketsPurchased: TypedContractEvent<
      TicketsPurchasedEvent.InputTuple,
      TicketsPurchasedEvent.OutputTuple,
      TicketsPurchasedEvent.OutputObject
    >;

    "TicketsTransferred(uint256,address,address,uint256)": TypedContractEvent<
      TicketsTransferredEvent.InputTuple,
      TicketsTransferredEvent.OutputTuple,
      TicketsTransferredEvent.OutputObject
    >;
    TicketsTransferred: TypedContractEvent<
      TicketsTransferredEvent.InputTuple,
      TicketsTransferredEvent.OutputTuple,
      TicketsTransferredEvent.OutputObject
    >;
  };
}
